# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 04 Apr 2014 17:26:20 +0000
*               @ALL          0
*               @user         8
